YYCFV030	;
	;
CalcularIntervaloData(dataInicio,dataFim,qtdeDias)	;
	if $get(dataFim)="" do
	.set dataFim=$HOROLOG
	else  set dataFim=$zdateh(dataFim,4,) ;Pegar hóraio atual
	;
	set dataInicio=$zdateh(dataInicio,4,)
	;set dataInicio = $ZDATETIME(dataInicio,4,)
	;
	if dataFim>dataInicio do
	.write dataFim," - ",dataInicio,!
	.write "Diferenca:",($piece(dataFim,",",1)-dataInicio),!
	;
	set qtdeDias=($piece(dataFim,",",1)-dataInicio)
	quit 1
